packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^22.13.11

  # Dev tooling
  eslint: ^9.23.0
  prettier: ^3.5.3
  typescript: ^5.8.2

  # Misc
  ky: ^1.8.0
  zod: ^3.24.2
  dayjs: ^1.11.13
  "@tanstack/react-query": ^5.76.1

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    react-native: 0.79.0
    react-native-web: 0.20.0
    nativewind: 4.1.23
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4

  next15:
    next: 15.3.0
    "@next/bundle-analyzer": ^15.3.0

  turbo:
    turbo: ^2.4.4
    "@turbo/gen": ^2.4.4
